DELETE FROM meal_entry;
DELETE FROM meal;
DELETE FROM food_item;
DELETE FROM goal;
DELETE FROM member;
DELETE FROM user;
ALTER TABLE meal AUTO_INCREMENT = 1;

ALTER TABLE user AUTO_INCREMENT = 1;

ALTER TABLE food_item AUTO_INCREMENT = 1;

ALTER TABLE goal AUTO_INCREMENT = 1;

ALTER TABLE member AUTO_INCREMENT = 1;
